### ISSUE TITLE
Mod ruins spawn eggs and any villager from Easy Villagers

### ISSUE THREAD

**Issue by aburone** [someaddons/HostileVillages#1]
**Describe the bug**
1) A villager spawn egg will yield skeletons, pandas and minecarts instead of a villager.
2) Additionally any villager stored with Easy Villagers becomes unusable because they too yield skeletons, etc

**To Reproduce**
1) Try to use a villager spawn egg
OR
2) Try to place a villager you Picked up with Easy Villagers

**Expected behavior**
1) I get a random villager
2) I get THAT villager

** Mod version **
hostilevillages-1.4-1.16.5.jar

**Comment by someaddons** [comment]
that is not a bug and fully intended, if villagers are disallowed in the config it'll replace them with mobs. If you want to have vanilla villagers enable them in the config
