### ISSUE TITLE
Mod only rereads config values between launches.

### ISSUE THREAD

**Issue by Kalikars** [someaddons/HostileVillages#10]
**Describe the bug**
Changes to the configuration file are only enacted between launches of Minecraft. This is not forge standard behavior.

**To Reproduce**
1. Use this config file: [pastebin link](https://pastebin.com/LZwXCfDS)
2. Create a world, use `/locate village` and teleport to village, confirm hostile village spawn.
3. Exit the world, change value "vanillaVillageChance" to 50, repeat step 2.

**Expected behavior**
Mod should reread config value upon new world creation and adjust vanilla village spawning chance to 50%. Instead, this change only occurs\* if Minecraft is exitted and relaunched.

\*Change does not correlate to proper percentage value. See related issue: [Editing "vanillaVillageChance" does not accurately reflect hostile village spawn percents.](https://github.com/someaddons/HostileVillages/issues/9)

**Mod version**
hostilevillages-3.0-1.16.5

**Comment by someaddons** [comment]
the config does reload, however some data, like the worldgen changes are pre-populated and wont be reloaded midgame.
