### ISSUE TITLE
Config Normal Village percentage doesn't work.

### ISSUE THREAD

**Issue by DaddyP1G** [someaddons/HostileVillages#11]
**Describe the bug**
When changing the first line of the Config from 0 to any number.  I used 75 every Village still spawns as Hostile. 

**To Reproduce**
1) change config to 75
2) search Villages

**Expected behavior**
Normal Villages to show up 75% of the time.

** Mod version **
3.1

** Logs **
No Crashes

**Comment by someaddons** [comment]
it works for me, changing it I see both zombie villages(those with cobweb) and normal villages(those without cobweb)
