### ISSUE TITLE
Help Wanted mod can't spawn villagers

### ISSUE THREAD

**Issue by MrEcko19** [someaddons/HostileVillages#12]
I understand that villages changes villagers for mobs to create the hostile villages, but villagers can't spawn with this other mod neither.

Guess the spawn egg of villagers it's completely change into a witch egg so just hoping there is another way to make this working?

Good job and thanks

**Comment by someaddons** [comment]
you need to change the config to allowe vanilla villages to spawn

**Comment by MrEcko19** [comment]
But this option will also make normal villages to spawn or just villagers in creative or by this other way?

I would be cool to mantain hostile villages spawn instead of normal ones, but also let you get villagers by egg spawn or with this others mod like Help Wanted
