### ISSUE TITLE
Zombie villager/spawn egg turns to other mobs and not zombie villagers

### ISSUE THREAD

**Issue by Xantill** [someaddons/HostileVillages#13]
Hi 
I play with this mod and ive found out that zombie villager spawn eggs does not spawn zombie villagers. And also when a zombie villager is unloaded and loaded it does the same. I cant find any help in the config file.
Do you think you can help me here?

**Comment by someaddons** [comment]
you need to set the allowVanillaVillagerSpawn to true in the config

**Comment by Xantill** [comment]
It is set to true. What i mean is if u wanna make cheaper trades and zombify and cure the zombie vill. If u unload a chunk and reload it the zombie vill are gonna turn into some other mobs.
