### ISSUE TITLE
Log Error: Hostile Villages Tag Was Loaded Too Early

### ISSUE THREAD

**Issue by Blunder-G** [someaddons/HostileVillages#14]
I checked out the Log and it says me this: 

Critical problem: hostilevillages.mixins.json:ITagMixin target net.minecraft.tags.ITag was loaded too early.

Log:
[latest.log](https://github.com/someaddons/HostileVillages/files/6986395/latest.log)

**Comment by someaddons** [comment]
can't reproduce that, must be some of your other mods causing this
