### ISSUE TITLE
[1.16.5, BUG] Zombie villagers explode into mobs instead, DESPITE THE ALLOW VILLAGERS CONFIG SET TO TRUE.

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/HostileVillages#19]
**Describe the bug**
As it says on the tin, My Vanilla zombie villager spawn eggs, when placed down they are immediately replaced with a bundle of semi-random mobs. Atleast, this is what is happening in my modpack currently: "Order of All Creation: Relic Hunters". The only way vanilla ZOMBIE villagers tend to remain existing is if spawned via a spawner made by a mod's structures, like mo structures jungle temple.

**To Reproduce**
Set allow vanilla villagers to true in the common config.
go into creative game and try to spawn a vanilla zombie villager.
get a blob of mobs instead.

**Expected behavior**
I should get a zombie villager... so I can test zombie villager conversion methods in my pack.

** Mod version **
hostilevillages-3.3-1.16.5.jar
Forge: 36.2.19

heres a shot of my config file instead. Should I try resetting it?

![image](https://user-images.githubusercontent.com/8104689/144573316-a6dca500-290b-4c77-8404-3cef778581af.png)

there was this however when searching if there was any config issues in the log.

[19:41:25] [main/ERROR]: Critical problem: hostilevillages.mixins.json:ITagMixin target net.minecraft.tags.ITag was loaded too early

[latest.log](https://github.com/someaddons/HostileVillages/files/7648024/latest.log)
.

**Comment by Darkmega18** [comment]
saw this going down when I loaded up a server just now.
![image](https://user-images.githubusercontent.com/8104689/144698834-ab26eca5-36ac-4db7-930e-5abf3aa406f0.png)
it's the same config thats from my client.

**Comment by someaddons** [comment]
added an exception for spawn eggs in 3.4
