### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by gglobensky** [someaddons/HostileVillages#2]
Hi, I have a modpack and as soon as I insert your mod, FML won't load properly and crash to the launcher.

**To Reproduce**
1. Install my modpack
2. Add Hostile Villages
3. Watch Crash

**Expected behavior**
To load properly

** Mod version **
version 1.4 with FML 36.1 on 1.16.5

[latest.log](https://github.com/someaddons/HostileVillages/files/6388906/latest.log)

Thanks for the great mods btw

**Comment by someaddons** [comment]
hm got a modlist? one of the other mod's coremod called `META-INF/asm/multipart.js` is crashing, it doesnt mention which mod though

**Comment by gglobensky** [comment]
Here is my modlist

https://pastebin.com/g65aAnpb

**Comment by someaddons** [comment]
yea seeing nothing standing out, so can't really tell which mod is having issues

**Comment by gglobensky** [comment]
I'll try to remove mods tonight and isolate which mod is problematic and tell you about it.

**Comment by someaddons** [comment]
hm gonna try with java 11

**Comment by someaddons** [comment]
I've uploaded a new version which should work with java 11

**Comment by gglobensky** [comment]
I forgot to specify it was OpenJ9 and not Hotspot. I think the problem lies with the JVM.

So if I try with Open J9 OpenJDK 11, it crashes.
If I try with Open J9 OpenJDK 8, it works.

If I try with Hotspot OpenJDK 8, it works.
If I try with Hotspot OpenJDK 11, it crashes.

**Comment by gglobensky** [comment]
I confirm that it works. It did not crash and I managed to see a village with enemies in it. 

Thank you very much!
