### ISSUE TITLE
Why does the villager removal config not shut off completely?

### ISSUE THREAD

**Issue by Darkmega18** [someaddons/HostileVillages#20]
**Describe the bug**
There are several situations where the mod is still deleting zombie villagers (I didn't test with normal villagers):
Cyclic Capture ball: When releasing villager , it explodes into mobs anyway.
Carry on: When picking up mobs with it and placing them back down in creative, same issue. explodes into mobs.
If this trend is the same all around, if another mod also implemented another mob capture mechanic, like alex mobs capture crates or perhaps mob cages configured to allow zombie villagers, then you'll probably have a similar issue.

So my thought is. why does this function exist in the first place, rather than just leaving it up to something like in control to block their spawn in a non-intrusive way on spawn? _(as with cyclic, this actually inadvertently creates a mob multiplier, cause the orb can't deploy the villager cause it keeps turning into mobs :V)_ and why, when I turn it off, does it still exist and not completely shut itself off and not handle villagers in any way at all? :V

**To Reproduce**
Capture villager using a mob based moving system like those mentioned above.
Make a lot of mobs instead.

**Expected behavior**
The whole villager/zombie villager system effectively deletes itself when turned off so this doesn't happen.

** Mod version **
_hostilevillages-3.4-1.16.5.jar_
and many-many others.

Not loggable.

**Comment by someaddons** [comment]
Its simply the base functionality of the mod, without you wont have zombie villages at all. If mods capture entities and not use proper spawn events for placing them again thats a bug on their side.
