### ISSUE TITLE
Stoneholm Underground Villages Are Hostile Too

### ISSUE THREAD

**Issue by SpencerMeow** [someaddons/HostileVillages#21]
Underground villages from the mod Stoneholm are also being affected by this mod. While there could be a feature to determine whether they are or aren't I definitely think they shouldn't be by default.

**To Reproduce**
1. Install this mod on Forge 1.16.5 + [Stoneholm, Underground Villages (Forge)](https://www.curseforge.com/minecraft/mc-mods/stoneholm-forge/files/3337788)
2. Observe how they too are overrun.

**Expected behavior**
Expected Stoneholm villages to be normal while only surface villages are hostile.

** Mod version **
3.4-1.16.5

**Comment by someaddons** [comment]
that is intended any villager and villages get replaced by default

**Comment by SpencerMeow** [comment]
> that is intended any villager and villages get replaced by default


I know but I want to be able to have Stoneholm villages remain normal
