### ISSUE TITLE
[Gamebreaking Bug] No "Zombie Villagers" spawn when added to the config file AND Zombies Spawn infinitely even in Peaceful Mode.

### ISSUE THREAD

**Issue by CalamitousEnd** [someaddons/HostileVillages#22]
**Describe the bug**
When the entity id "minecraft:zombie_villager" is added to villageEntityTypes pairs array in the configuration file, the game fails to spawn them and instead spawns a bunch of zombies (or whatever the first entity in the pairs is) to compensate for it, and will continue to spawn the 1st entity indefinitely, even if you set the game to peaceful mode.

**To Reproduce**
1. Go to "hostilevillages-common.toml" and add "minecraft:zombie_villager" to one of the "villageEntityTypes" pairs. (ex I used: "minecraft:zombie;minecraft:zombie_villager;3;100")

2. Load a world and look for a village.

**Expected behavior**
Zombie Villagers spawn in Villages if specified in the "VillageEntityTypes" array.

** Mod version **
1.18.1-3.6

** Logs **
Latest/Crash log

https://gist.github.com/CalamitousEnd/a36d289f96a1950178dde3ddd0fc645b

**Comment by CalamitousEnd** [comment]
`
["Hostile Villages settings"]
	#Percentage of how likely normal,non-zombie villages are to spawn. default: 0
	#Range: 0 ~ 100
	vanillaVillageChance = 10
	#Set higher to increase the generated population of the hostile village, default: 5
	#Range: 1 ~ 100
	hostilePopulationSize = 5
	#Whether to generate extra loot for the village, default: true
	generateLoot = false
	#Turn on debug messages for spawning, default: false
	debugLog = true
	#Disables entities beeing unable to despawn after they get an item equipped, default: true
	disableNoEntityDespawnWhenPickingItem = true
	#List of loottables to use, default: minecraft:chests/simple_dungeon
	loottables = []
	#Whether to allow vanilla villagers to spawn at all. If enabled then hostile villages will get a villager spawn egg added to their loot. default: false
	allowVanillaVillagerSpawn = true
	#List of entity pairs which spawn in villages. Format = entity1;entity2;5;6   5 is the chance of entity2(one in five), 6 is the total weight of this whole entry to be chosen
	villageEntityTypes = ["minecraft:zombie;minecraft:zombie_villager;3;100"]
	#Additional structures to add as houses for spawning zombie villages, default: []. Example for bountiful and waystones support: ["bountiful:village/common/bounty_gazebo", "waystones:village/common/waystone"]
	additionalStructures = []
	#Set higher to increase the amount of additional structures generated, note those replace houses, default: 2
	#Range: 1 ~ 100
	additionalStructuresWeight = 2

`

This is my entire config settings.

**Comment by someaddons** [comment]
yea using zombie villagers as spawning in a zombie village creates a loop. Added some code to avoid it in 3.7

**Comment by CalamitousEnd** [comment]
Thank you so much. I appreciate you being so quick to fix it. So now I should be able to let Zombie Villagers spawn in hostile villages right?
