### ISSUE TITLE
[Bug]: Igloos are affected by the Hostile Villagers Mod.

### ISSUE THREAD

**Issue by CalamitousEnd** [someaddons/HostileVillages#23]
### Describe the bug you're experiencing

Igloos seem to be affected by the abandoned village changes. What I mean by that is, I have a Vindicator and an Evoker Spawning where a single Zombie Villager is supposed to be. I don't believe this is intended behavior and it breaks the idea of using an Igloo to start your own village.

![2022-02-24_09 03 50](https://user-images.githubusercontent.com/41867693/155539905-42bc1e78-b8ae-4bab-964c-6b3076e5099f.png)

### Reproducability

1. Add any mob pairs to the "villageEntityTypes"
2. Find an Igloo with a TrapDoor.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

https://gist.github.com/CalamitousEnd/375b3fbc40862d8affae69aae0f47170

**Comment by CalamitousEnd** [comment]
Is this something you can fix?

**Comment by someaddons** [comment]
no not really, it doesnt know which structure it is when replacing the entities
