### ISSUE TITLE
[Bug]: All Villagers existed before installing the mod disappeared completely

### ISSUE THREAD

**Issue by babacon88** [someaddons/HostileVillages#25]
### Describe the bug you're experiencing

Before getting this mod I was playing on a world with 3 villages and its villagers, after installing the mod, it seems it removed every villager out there. 
There should coded that preexisting villager remain untouched

### Reproducability

Create a world and find a village without the mod, then install it

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/babacon88/8abd817aaa7337c9971aa620364270c5

**Comment by someaddons** [comment]
its not a bug, its intended by default this mod replaces all villagers. If you dont want that oyu need to adjust the config
