### ISSUE TITLE
Suggestion-config option to change village spawn rate

### ISSUE THREAD

**Issue by PurpleHel** [someaddons/HostileVillages#3]
It'd be useful if along with setting a percentage of the villages to be hostile, you could also increase village spawn rate. That way, having some hostile villages doesn't completely screw you over on having normal villages too. It's bad enough when you have a seed with only a couple villages in 1000 chunks. It'd be extra frustrating to only have two villages and they're both hostile. Or alternatively, pack makers could go the other way and reduce village spawn rates, if they wanted!
I dunno, maybe that's outside of what you think fits the mod, but it seemed thematic to me.

**Comment by someaddons** [comment]
hm I'll look into if one could easily adjust the spawnrate. Though if you enabled vanilla villagers the hostile villages are likely to contain loot with a villager spawn egg, so you can even get them from a taken over village.

**Comment by PurpleHel** [comment]
I think it was pretty trivial in 1.12, I have no idea how it is in 1.16 tho. Realistic terrain generator did it, as did a number of other mods.
Good to know that hostile villages have spawn eggs tho! That makes it a bit less of a potential problem to have hostile villages, just have to clear them and then spawn villagers!

**Comment by someaddons** [comment]
ye getting some villagers when the config for them is enabled should be a non-issue with the spawn eggs :)
