### ISSUE TITLE
[Bug]:  AllowVanillaVillagerSpawn config not working correctly (again?)

### ISSUE THREAD

**Issue by winnetrie83** [someaddons/HostileVillages#31]
### Describe the bug you're experiencing

"allowVanillaVillagerSpawn": {
    "desc:": "Whether to allow vanilla villagers to spawn at all. default: false",
    "allowVanillaVillagerSpawn": false
    
    setting it to true doesn't seem to convert any villager at all 
    I checked multiple fresh generated villages and all were friendly. None were hostile.
    Settings it to false converts all villagers to hostile mobs and converts any spawn in villager to a hostile mob ( wich is obviously intended ofcourse)
    
    This is NOT for MC 1.19. It is MC 1.20.1, but the template doesn't let me choose that.

### Reproducability

change settings and test.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://pastebin.com/7JUVBkt7

**Comment by someaddons** [comment]
Fixed in 5.4
