### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gglobensky** [someaddons/HostileVillages#4]
I'm sorry to ask here as I'm not sure it's the right place but I was wondering if there would be villagers spawn eggs (I read in an other issue that there were such items) in hostile villages if I set the vanillaVillageChance to 85 and allowVanillaVillagerSpawn to true. 

I normally would have looked into the jar to find what you inject into the loottables but yours seems formed in a way that I'm not used to.

**Comment by someaddons** [comment]
the allowVanillaVillagerSpawn to true manually adds the spawn egg after loot generation

**Comment by gglobensky** [comment]
Thank you very much for the info. I thought it was to allow regular villagers spawns in vanillaVillages.

May I propose addVillagerEggsToLoot for the config, this would make it clear as day IMO.

**Comment by someaddons** [comment]
ye I'll add a comment to the config, to make it a bit clearer :D
