### ISSUE TITLE
Not obeying config

### ISSUE THREAD

**Issue by Zygus42** [someaddons/HostileVillages#5]
We have these settings on our server:
	#Percentage of how likely normal,non-zombie villages are to spawn. default: 0
	#Range: 0 ~ 100
	vanillaVillageChance = 70
	#Set higher to increase the generated population of the hostile village, default: 5
	#Range: 1 ~ 100
	hostilePopulationSize = 5

And yet every single village is hostile.

It could be because Terraforged is also trying to set village spawn ?  Unsure.

hostilevillages-1.8-1.16.5
TerraForged-1.16.5-0.2.10
forge-1.16.5-36.1.12-installer

Also, many of the village mobs have no AI - they just stand there and do nothing, even when you hit them.
[latest.log](https://github.com/someaddons/HostileVillages/files/6464033/latest.log)

**Comment by someaddons** [comment]
Did you set allowVanillaVillagerSpawn to true? else no villagers will spawn and they get replaced with mobs.
Which mobs soecifically do not attack?
