### ISSUE TITLE
bugs with the mod

### ISSUE THREAD

**Issue by NixityNull** [someaddons/HostileVillages#6]
The mod works fine, there are just a few things you might want to polish up.

- Mod id and Config does not appear when using configured (https://www.curseforge.com/minecraft/mc-mods/configured)
- Villages tend to only spawn on the border of biomes, often looking out of place due to snow or sand paths being pushed outward into the neighboring biome.
- non-humanoid mobs break doors and are equipped with leather hats despite being incapable of actually displaying armor models.

**Comment by someaddons** [comment]
Village generation is completly vanilla, all this mod does is tell vanilla to use the zombie version, the leather hats thing is probably an error. Mobs are intentionally able to break doors right after they spawned, so that they don't get stuck in some custom house with doors

**Comment by someaddons** [comment]
fixed the leather drops

**Comment by NixityNull** [comment]
Its just so strange that every time I used /locate on a village it ended up on the border of two biomes... note that i was using default configs and located at least 3 separate villages in 3 separate biomes.

**Comment by NixityNull** [comment]
Nevermind, the problem with villages spawning on the edges of biomes was caused by other mods
