### ISSUE TITLE
Editing "vanillaVillageChance" does not accurately reflect hostile village spawn percents.

### ISSUE THREAD

**Issue by Kalikars** [someaddons/HostileVillages#9]
**Describe the bug**
Editing the int value for "vanillaVillageChance" to be above 0 along with "allowVanillaVillagerSpawn" = true in the config does not accurately reflect the percentage chance for villages to spawn.

**To Reproduce**
1. Use these configuration files (remove _<number> from file name): [Gist Link](https://gist.github.com/Kalikars/a985dcbaa6a2ebbdbac7b0c6b41845ce.js)
2. Create a new world (random seed, default options, creative).
3. Use `/locate village` and teleport to village, check if hostile, `/tp ~ ~ ~1000`, and repeat x10.
4. Shut down minecraft, swap config files, repeat step 2-3 for each config.

**Expected behavior**
✔With value = 0: Vanilla villages should never spawn. This config value **works** as intended.
❌With value = 50: Vanilla villages should spawn 50% of the time. In my testing, vanilla villages spawned 12/12 times (expected: 6/12).
❌With value > 0: Vanilla villages should sometimes spawn, with smaller values making this less likely. At value = 1, vanilla villages spawned 0/10 times (expected: 0.1/10, so this **works** as intended). At value = 10, vanilla villages spawned 8/10 times (expected: 1/10). 

There may be a mathematical error with the way percent values are calculated that are making larger values much more heavily weighted than they should be. It may be beneficial to change the native config value to a double and utilize it that way instead of casting as an int.

**Mod version**
hostilevillages-3.0-1.16.5

**Comment by someaddons** [comment]
fixed in 3.1
